name: Clang Format Check

on:
  pull_request:
    branches:
      - main

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Clang Format
        run: sudo apt-get install -y clang-format

      - name: Run Clang Format
        run: |
          # Find all C and C++ header + definition files and format them
          find ./MCB-project -name "*.c" -o -name "*.cc" -o -name "*.cpp" \
          -o -name "*.h" -o -name "*.hh" -o -name "*.hpp" |
          xargs clang-format -i

      - name: Check for formatting changes
        run: |
          # If there are any differences after formatting, this will fail
          git diff --exit-code
